version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1010abab
      POSTGRES_USER: siemens-project
      POSTGRES_DB: multi-sim-psqldb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}